version: "3.5"
services:
  vis-ui:
    environment:
      PUBLIC_URL: /vis/ui
    volumes:
      - '../../ui/src:/app/src'
      - '../../ui/public:/app/public'
      - '../../ui/config:/app/config'
      - '../../ui/scripts:/app/scripts'
